### ISSUE TITLE
Proper C++ exception handling

### ISSUE THREAD

**Issue by hirschenberger** [strawlab/pylon-cxx#10]
I have a problem with some code that has to reconfigure the exposure value after every grabbed image. To do this the grabbing must be stopped, value set, grabbing started...

The problem is, that occasionally the C++ code throws a `GenICam_3_1_Basler_pylon::RuntimeException` that can't be caught in rust and so my app panics.

I looked at the code and it seems, although `fn float_node_set_value(node: &UniquePtr<CFloatParameter>, value: f64) -> Result<()>;` returns a Result, it seems it's not really created on errors (exceptions) in the FFI code.

Wouldn't it make sense to try-catch all C++ FFI functions return a `Result::Err` value on exceptions to make the user handle the error in Rust-land?

**Comment by astraw** [comment]
Catching all C++ exceptions and translating them to a rust `PylonError` should happen, but evidently does not.

I notice some cruft which is apparently unused like the `trycatch` C++ function. It would be great to wire this up to work as you suggest.

**Comment by hirschenberger** [comment]
`GenICam_3_1_Basler_pylon::RuntimeException` is an Alias for `GenICam::RuntimeException` which is derived from `Pylon::GenericException`. So one exception handler is sufficient.

**Comment by hirschenberger** [comment]
@astraw Can you please look at this, I'd need that fix in a project
