### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by hirschenberger** [strawlab/pylon-cxx#13]
Hey Andrew,

I'd like to discuss if we should enhance this crate with additional functionality (behind a feature gate) or if you want to keep it as small as possible.

I have a nice extension trait and implementation for `InstantCamera` which adds async stream functionality like this, which are useful for Linescan cams.

```rust
pub trait LineCameraExt: Stream {
    /// Grab until a future resolves joining all images to one.
    async fn join_until(
        &mut self,
        until: impl Future,
        max_size: Option<usize>,
    ) -> Result<DynamicImage>;

    /// Start grabbing when a future resolves till another future resolves, joining all images to one
    async fn join_from_until(
        &mut self,
        start: impl Future,
        end: impl Future,
        max_size: Option<usize>,
    ) -> Result<DynamicImage>;
}
```

Which can be used like this:

```
let start = tokio::time::sleep(Duration::from_secs(2));
let duration = tokio::time::sleep(Duration::from_secs(3));
let img = cam.join_from_until(start, duration, None).await?;
```

The start and until futures can be all kinds of sources like: channel messages, hardware switches, network messages...

Implementations for area cameras and more stream utility functions are possible.

For this above example, the `futures` crate is required which provide the `StreamExt` trait and I also use the `image` crate. Returning GrabResults does not work, because the camera has an internal number of buffers and is blocking after all of them are used. So the pixelbuffer must be copied to an external pixelbuffer.

Things to discuss:

* Would you like to extend the crate with functionality like this?

* What is a good general-purpose and well established pixelbuffer crate to use?

**Comment by astraw** [comment]
Hi Falco,

My feeling is that this belongs better at a higher level. In other words, I think it doesn't fit to my goal of a minimal but solid `pylon-cxx` crate that takes care of the low-level wrapping of the Pylon library. Is there any functionality that would be lost by maintaining a things in a separate crate?

**Comment by hirschenberger** [comment]
Yes, you're right. It makes sense to encapsulate that highlevel functionality in it's own crate. The stream implementation needs to be in pylon-cxx because it uses lowlevel features (the filedesctiptor).

So I'd create a companion crate to pylon-cxx. Maybe I reuse the pylon name from my own old crate.

What would you say is a good pixelbuffer for that usecase? 

* Stick to the widespread but huge `ìmage`create and return a `DynamicImage` dependent on the camera pixeltype.
* Use the static typed `ImageBuffer<>` from the `image` crate and return an Err() if the camerra's pixel type does not match the requested type.
* Crate an own datatype with a raw buffer, width, height and stride.
* Use the zero-deps [imgref](https://crates.io/crates/imgref/1.10.1) crate

**Comment by astraw** [comment]
Even though I strongly support the goals of imgref (which I just discovered thanks to your comment), a quick search through their code does find any matches on "bayer" or "yuv" so I'm afraid as of not it would not work well for our use of color cameras. The `image` crate [does not support bayer formats](https://github.com/image-rs/image/issues/1084). You could consider my [`machine-vision-formats`](https://crates.io/crates/machine-vision-formats), but it may also have shortcomings and certainly does not have widespread use. (I would certainly be open to improvement on it.)

In the end, I think a simple datatype that does just what you need right now may be good enough and quick to implement. If one can extract the `Vec<u8>` data along with shape data and pixel type, that should be enough to do anything with it without needing to copy big arrays around.

**Comment by hirschenberger** [comment]
Hello @astraw FYI I relaunched the Pylon crate with some utility functions.

https://gitlab.com/hirschenberger/pylon

Maybe the typestate-pattern-based camera structs are interesting to backport? From time to time I run into the problem, that I get a panic when I start grabbing on a cam that's already grabbing. That problem can be prevented at all by using typestates.

**Comment by astraw** [comment]
@hirschenberger thanks for the note. I will check it out.
