### ISSUE TITLE
Which cameras

### ISSUE THREAD

**Issue by Resonanz** [strawlab/pylon-cxx#14]
is not obvious which Basler cameras this software is applicable to.

**Comment by astraw** [comment]
This crate is a wrapper of the [Pylon SDK by Basler](https://www.baslerweb.com/en/software/pylon/sdk/). If Pylon supports the camera, this crate should, too. (Of course whether it actually does is different.) If you find a list of which cameras are supported by the Pylon SDK, I would be happy to consider a pull request adding this to the documentation. For now I will close this issue.

**Comment by Resonanz** [comment]
Thanks for the update. I have a Basler ACE camera so would be curious to see whether it would work or not. I'll have a poke around your code and see what I find. Thanks.

**Comment by astraw** [comment]
Yes, we use Basler Ace and Ace2 frequently with this crate.

**Comment by Resonanz** [comment]
Hi Andrew, I have downloaded the Linux SDK and had a go at installing it, but the paths are probably not set correctly on my machine. "No such file or directory"

```
warning: pylon-cxx@0.4.1:     1 | #include "pylon/PylonIncludes.h"
```

Are you setting environment variables to make things work?

I tried placing the extracted pylon SDK into /opt/pylon and in the src/ Rust folder.

Thanks in advance for any help.

**Comment by hirschenberger** [comment]
> Hi Andrew, I have downloaded the Linux SDK and had a go at installing it, but the paths are probably not set correctly on my machine. "No such file or directory"
> 
> ```
> warning: pylon-cxx@0.4.1:     1 | #include "pylon/PylonIncludes.h"
> ```
> 
> Are you setting environment variables to make things work?
> 
> I tried placing the extracted pylon SDK into /opt/pylon and in the src/ Rust folder.
> 
> Thanks in advance for any help.

You must first source the `pylon-setup-env.sh` script to set some environment variables in your current shell like this:

```
source /opt/pylon/bin/pylon-setup-env.sh /opt/pylon
```

**Comment by Resonanz** [comment]
That definitely helped. Now I am getting:

```
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/examples/show-version`
target/debug/examples/show-version: error while loading shared libraries: libpylonbase.so.8.0: cannot open shared object file: No such file or directory
```

**Comment by hirschenberger** [comment]
You must tell your OS where to search for dynamic libraries.
You can either set the `LD_LIBRARY_PATH` variable to `/opt/pylon/lib`

```
export LD_LIBRARY_PATH=/opt/pylon/lib
```
or make it a global library search path by adding a file with the above path to a new file `/etc/ld.so.conf.d/pylon.conf`.

**Comment by Resonanz** [comment]
Thanks for your help guys. I got the camera working as far as your software is reading from it using the example "grab".

If I write up the Ubuntu install instructions, would you add them to your page?
