### ISSUE TITLE
Tiny issue

### ISSUE THREAD

**Issue by Resonanz** [strawlab/pylon-cxx#16]
Example files use hyphens except for grab_modded.rs which uses an underscore.

Just tried compiling and received error:

```
cargo run --example grab_modded
```

```
error[E0308]: mismatched types
   --> examples/grab_modded.rs:47:20
    |
47  |     bb.checked_add(arr);
    |        ----------- ^^^ expected `u8`, found `[u8; 4000000]`
    |        |
    |        arguments to this method are incorrect
```

**Comment by hirschenberger** [comment]
Where do you see grab_modded.rs?

**Comment by Resonanz** [comment]
Mmmm, I thought I had a fresh install from Github but thinking now that that file must have been a hangover from playing around many months back. It all makes sense now. Apologies.
