### ISSUE TITLE
In windows, an environment variable will be added after installing pylon.

### ISSUE THREAD

**Issue by WingOwO** [strawlab/pylon-cxx#5]
In build.rs, the pylon_dev_dir(line: 192)can be assigned as PYLON_DEV_DIR.
![a](https://user-images.githubusercontent.com/49347091/142817822-d68a5e78-cc74-4466-8449-58ebc98805cb.png)

**Comment by astraw** [comment]
Thanks, I hadn't noticed that. Released in 0.2.1.
