### ISSUE TITLE
How to connect to a camera with a specific IP address?

### ISSUE THREAD

**Issue by JannikP** [strawlab/pylon-cxx#8]
I'm trying to connect to a camera from a docker container. Although I'm able to ping the camera from inside the container, connecting to it via `let camera = factory.create_first_device()?;` results in no device found.

Now I want to try to connect to the camera by specifing the IP address directly. With `pypylon` this would work like this:

```python
ip_address = '192.168.178.63'
info = pylon.DeviceInfo()
info.SetPropertyValue('IpAddress', ip_address)
camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice(info))
```

How to achieve this using `pylon-cxx`?

**Comment by hirschenberger** [comment]
Usually you configure your camera with the `IpConfigurator` tool that comes with the pylon sdk. You have to configure the camera, then it will be found by the `TlFactory`.

There's 3 modes that the camera can operate in:

* **Static IP**, which means you give the camera a static address that works in your network settings
* **Auto IP**, this is a fixed range of addresses `169.254.x.y` and the camera will choose one in that range, you also have to configure your network adapter's address to this range. (netmask 255.255.0.0)
* **DHCP**, the camera bradcasts and requests a network address from a DHCP-server in your network.

**Comment by JannikP** [comment]
The camera is correctly configured, I check it with Pylon Viewer from a different computer on the same network.

In the meantime I managed to connect to the camera with `let camera = factory.create_first_device()?;`. The problem was the Docker network configuration. A MACVLAN is required to reach the camera from inside a Docker container. 

However my questions still holds. How to connect to a specific camera identified by its IP address? For example when there are multiple cameras on the same network.

**Comment by hirschenberger** [comment]
Just iterate over all cameras with `enumerate_devices` and pick the one with the required IP, DeviceId...

**Comment by astraw** [comment]
@JannikP I guess there are just a few API calls simply not implemented that you need. I haven't looked into this directly but I hope if you are already experienced with Rust you could copy-and-paste some existing calls and modify as needed to support the missing functionality. We could then merge this back in.

**Comment by JannikP** [comment]
Ok, got it. In case somebody else tries to achieve the same thing:

```Rust
let requested_ip = "192.168.178.63"; // e. g. from configuration
let info = factory.enumerate_devices()?
    .into_iter()
    .filter(|info| info.property_value("IpAddress").unwrap_or_default() == requested_ip)
    .next()
    .ok_or(anyhow!("Camera not found"))?;
let camera = factory.create_device(&info)?;
```
